### ISSUE TITLE
401 错误

### ISSUE THREAD

**Issue by xjr7670** [aliyun/aliyun-datahub-sdk-python#24]
报错如下：

```
Traceback (most recent call last):
  File "test_datahub.py", line 40, in <module>
    pj = test_project(dh)
  File "test_datahub.py", line 25, in test_project
    project = dh_obj.get_project('datahub_sjzypt_dpzbssjr_p_1')
  File "/usr/lib/python2.7/site-packages/datahub/core.py", line 99, in get_project
    return self._datahub_impl.get_project(project_name)
  File "/usr/lib/python2.7/site-packages/datahub/implement.py", line 72, in get_project
    content = self._rest_client.get(url)
  File "/usr/lib/python2.7/site-packages/datahub/rest.py", line 324, in get
    return self.request(HTTPMethod.GET, url, **kwargs)
  File "/usr/lib/python2.7/site-packages/datahub/rest.py", line 315, in request
    status_code, request_id, '',)
datahub.exceptions.DatahubException: status_code: 401, request_id: , error_code: , error_msg: Decode json message error, content: <?xml version="1.0" encoding="UTF-8"?>
<Error>
	<Code>InvalidAuthorization</Code>
	<Message><![CDATA[ODPS-0410042:Invalid signature value - Curl perform failed]]></Message>
	<RequestId>5C72047D38FEF58A549C872A</RequestId>
	<HostId>localhost</HostId>
</Error>
```

看提示说是无效的认证，但是代码里面用到的 access_id 和 access_key 在网页中是可以用来登录 datahub 的。不知道这是什么问题

**Comment by noosc** [comment]
endpoint不对，返回的内容都是odps的信息
