### ISSUE TITLE
get_connector catch error KeyError: 'StartSequence'

### ISSUE THREAD

**Issue by yqfclid** [aliyun/aliyun-datahub-sdk-python#27]
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/datahub/core.py", line 406, in get_connector
    return self._datahub_impl.get_connector(project_name, topic_name, connector_type)
  File "/usr/lib/python2.7/site-packages/datahub/implement.py", line 327, in get_connector
    result = GetConnectorResult.parse_content(content)
  File "/usr/lib/python2.7/site-packages/datahub/models/results.py", line 830, in parse_content
    shard_contexts = [ShardContext.from_dict(item) for item in content['ShardContexts']]
  File "/usr/lib/python2.7/site-packages/datahub/models/shard.py", line 159, in from_dict
    return cls(dict_['ShardId'], dict_['StartSequence'], dict_['EndSequence'], dict_['CurrentSequence'])
KeyError: 'StartSequence'

**Comment by noosc** [comment]
these keys dont exists any longer from server version 2.14, sdk is updated to 2.15 now
